import type { BadgeDefinition, BadgeGrade } from "./types";

export const BADGE_DEFINITIONS: BadgeDefinition[] = [
  // ============================================================
  // 일일 (daily) — 매일 반복 획득 가능
  // ============================================================
  {
    id: "daily-first",
    name: "첫 발걸음",
    description: "오늘 할일을 1개 이상 완료했어요!",
    hint: "할일을 딱 하나만 끝내봐! 시작이 반이야~ 🐣",
    emoji: "👶",
    grade: "common",
    category: "daily",
    condition: (ctx) => ctx.todayCompleted >= 1,
    repeatable: true,
  },
  {
    id: "daily-half",
    name: "반은 했다!",
    description: "오늘 할일의 절반 이상을 완료했어요!",
    hint: "오늘 할일의 반만 해보자! 반만~! ✌️",
    emoji: "👍",
    grade: "common",
    category: "daily",
    condition: (ctx) => ctx.todayTotal > 0 && ctx.todayRate >= 0.5,
    repeatable: true,
  },
  {
    id: "daily-perfect",
    name: "오늘 다 했다!",
    description: "오늘 할일을 모두 완료했어요!",
    hint: "오늘 할일을 전~부 끝내면 딸 수 있어! 화이팅! 🌟",
    emoji: "🌟",
    grade: "common",
    category: "daily",
    condition: (ctx) => ctx.todayTotal > 0 && ctx.todayRate === 1,
    repeatable: true,
  },
  {
    id: "daily-busy",
    name: "바쁜 하루",
    description: "할일이 5개 이상인 날 올클리어!",
    hint: "할일이 5개 이상인 날에 전부 클리어! 바쁜데 대단해~ 💪",
    emoji: "💪",
    grade: "rare",
    category: "daily",
    condition: (ctx) => ctx.todayTotal >= 5 && ctx.todayRate === 1,
    repeatable: true,
  },
  {
    id: "daily-mega",
    name: "대장 미션",
    description: "할일이 8개 이상인 날 올클리어!",
    hint: "할일 8개 이상을 한 방에?! 대장만 가능해! 🦸",
    emoji: "🦸",
    grade: "epic",
    category: "daily",
    condition: (ctx) => ctx.todayTotal >= 8 && ctx.todayRate === 1,
    repeatable: true,
  },
  {
    id: "daily-ultra",
    name: "완전 정복",
    description: "할일이 10개 이상인 날 올클리어!",
    hint: "할일 10개를 전부?! 두 자릿수 올클은 진짜 대단해! 🔟",
    emoji: "🔟",
    grade: "epic",
    category: "daily",
    condition: (ctx) => ctx.todayTotal >= 10 && ctx.todayRate === 1,
    repeatable: true,
  },
  {
    id: "daily-monster",
    name: "끝판왕의 하루",
    description: "할일이 12개 이상인 날 올클리어!",
    hint: "12개나 되는 할일을 다 해치우다니... 넌 끝판왕이야! 👹",
    emoji: "👹",
    grade: "legendary",
    category: "daily",
    condition: (ctx) => ctx.todayTotal >= 12 && ctx.todayRate === 1,
    repeatable: true,
  },
  {
    id: "daily-god",
    name: "할일의 왕",
    description: "할일이 15개 이상인 날 올클리어!",
    hint: "15개 올클?! 이건 인간의 영역을 넘어선 거야... 🙇",
    emoji: "🙇",
    grade: "legendary",
    category: "daily",
    condition: (ctx) => ctx.todayTotal >= 15 && ctx.todayRate === 1,
    repeatable: true,
  },

  // ============================================================
  // 연속 (streak) — 1회만 획득
  // ============================================================
  {
    id: "streak-3",
    name: "3일 연속!",
    description: "3일 연속 모든 할일을 완료했어요!",
    hint: "3일 연속으로 올클리어 해봐! 불꽃이 붙을 거야 🔥",
    emoji: "🔥",
    grade: "common",
    category: "streak",
    condition: (ctx) => ctx.streak >= 3,
    repeatable: false,
  },
  {
    id: "streak-5",
    name: "5일 연속!",
    description: "5일 연속 올클리어! 습관이 생기고 있어요!",
    hint: "5일 연속 올클! 평일을 완벽하게 🔥🔥",
    emoji: "🔥",
    grade: "common",
    category: "streak",
    condition: (ctx) => ctx.streak >= 5,
    repeatable: false,
  },
  {
    id: "streak-7",
    name: "일주일 완주!",
    description: "7일 연속 올클리어! 대단해요!",
    hint: "일주일 내내 올클리어! 할 수 있겠지?! 🏆",
    emoji: "🏆",
    grade: "rare",
    category: "streak",
    condition: (ctx) => ctx.streak >= 7,
    repeatable: false,
  },
  {
    id: "streak-10",
    name: "10일 연속!",
    description: "10일 연속 올클리어! 멈출 수 없어!",
    hint: "10일 동안 하루도 빠짐없이! 진짜 끈기가 필요해 💫",
    emoji: "💫",
    grade: "rare",
    category: "streak",
    condition: (ctx) => ctx.streak >= 10,
    repeatable: false,
  },
  {
    id: "streak-14",
    name: "2주 연속!",
    description: "14일 연속 올클리어! 이제 습관이에요!",
    hint: "2주 연속 올클리어! 습관이 되려면 여기까지! ⚡",
    emoji: "⚡",
    grade: "rare",
    category: "streak",
    condition: (ctx) => ctx.streak >= 14,
    repeatable: false,
  },
  {
    id: "streak-21",
    name: "3주 연속!",
    description: "21일 연속 올클리어! 완벽한 습관!",
    hint: "21일이면 습관이 완성된대! 도전해볼래? 🌊",
    emoji: "🌊",
    grade: "epic",
    category: "streak",
    condition: (ctx) => ctx.streak >= 21,
    repeatable: false,
  },
  {
    id: "streak-30",
    name: "한 달의 기적",
    description: "30일 연속 올클리어! 정말 놀라워요!",
    hint: "한 달(30일) 연속 올클리어! 기적을 만들어봐! 👑",
    emoji: "👑",
    grade: "epic",
    category: "streak",
    condition: (ctx) => ctx.streak >= 30,
    repeatable: false,
  },
  {
    id: "streak-45",
    name: "45일 철벽!",
    description: "45일 연속 올클리어! 흔들림 없는 의지!",
    hint: "한 달 반(45일) 연속! 철벽 같은 의지력이 필요해! 🧱",
    emoji: "🧱",
    grade: "epic",
    category: "streak",
    condition: (ctx) => ctx.streak >= 45,
    repeatable: false,
  },
  {
    id: "streak-60",
    name: "두 달의 전설",
    description: "60일 연속 올클리어! 전설이 되고 있어요!",
    hint: "60일 연속?! 진짜 전설만 가능한 거야... 🐉",
    emoji: "🐉",
    grade: "legendary",
    category: "streak",
    condition: (ctx) => ctx.streak >= 60,
    repeatable: false,
  },
  {
    id: "streak-90",
    name: "90일 초인",
    description: "90일 연속 올클리어! 석 달을 버텼어!",
    hint: "3개월(90일) 연속! 이건 초인의 영역이야... 🧬",
    emoji: "🧬",
    grade: "legendary",
    category: "streak",
    condition: (ctx) => ctx.streak >= 90,
    repeatable: false,
  },
  {
    id: "streak-120",
    name: "120일 불멸",
    description: "120일 연속 올클리어! 4개월 내내!",
    hint: "4개월(120일) 연속 올클?! 불멸의 기록... 🔱",
    emoji: "🔱",
    grade: "legendary",
    category: "streak",
    condition: (ctx) => ctx.streak >= 120,
    repeatable: false,
  },
  {
    id: "streak-180",
    name: "반년의 신화",
    description: "180일 연속 올클리어! 반년을 정복했어!",
    hint: "6개월(180일) 연속... 이건 신화야. 감히 도전할 수 있어? 🦄",
    emoji: "🦄",
    grade: "legendary",
    category: "streak",
    condition: (ctx) => ctx.streak >= 180,
    repeatable: false,
  },
  {
    id: "streak-270",
    name: "끝까지 간 자",
    description: "270일 연속 올클리어! 처음부터 끝까지 완벽!",
    hint: "3월부터 12월까지 하루도 안 빠지고?! 이건 전설 중의 전설... 👼",
    emoji: "👼",
    grade: "legendary",
    category: "streak",
    condition: (ctx) => ctx.streak >= 270,
    repeatable: false,
  },

  // ============================================================
  // 마일스톤 — 누적 완료 개수
  // ============================================================
  {
    id: "total-10",
    name: "10개 돌파",
    description: "총 10개의 할일을 완료했어요!",
    hint: "할일을 총 10개 끝내봐! 두 자릿수 진입~ 🎯",
    emoji: "🎯",
    grade: "common",
    category: "milestone",
    condition: (ctx) => ctx.totalCompleted >= 10,
    repeatable: false,
  },
  {
    id: "total-30",
    name: "30개 돌파",
    description: "총 30개의 할일을 완료했어요!",
    hint: "누적 30개 완료! 꾸준히 하면 금방이야 🎯",
    emoji: "🎯",
    grade: "common",
    category: "milestone",
    condition: (ctx) => ctx.totalCompleted >= 30,
    repeatable: false,
  },
  {
    id: "total-50",
    name: "50개 돌파",
    description: "총 50개의 할일을 완료했어요!",
    hint: "반백! 할일 50개를 모아봐! 🎯",
    emoji: "🎯",
    grade: "common",
    category: "milestone",
    condition: (ctx) => ctx.totalCompleted >= 50,
    repeatable: false,
  },
  {
    id: "total-100",
    name: "100개 돌파",
    description: "총 100개의 할일을 완료! 세 자릿수!",
    hint: "드디어 세 자릿수! 할일 100개를 클리어해봐! 💯",
    emoji: "💯",
    grade: "rare",
    category: "milestone",
    condition: (ctx) => ctx.totalCompleted >= 100,
    repeatable: false,
  },
  {
    id: "total-200",
    name: "200개 돌파",
    description: "200개 완료! 멈출 수 없는 실행력!",
    hint: "할일 200개 완료! 실행력이 대단해~ 🏅",
    emoji: "🏅",
    grade: "rare",
    category: "milestone",
    condition: (ctx) => ctx.totalCompleted >= 200,
    repeatable: false,
  },
  {
    id: "total-300",
    name: "300개 돌파",
    description: "300개 완료! 한 달치를 해냈어!",
    hint: "한 달치(300개)를 모두 해치웠어! 🥈",
    emoji: "🥈",
    grade: "rare",
    category: "milestone",
    condition: (ctx) => ctx.totalCompleted >= 300,
    repeatable: false,
  },
  {
    id: "total-500",
    name: "500개 돌파",
    description: "500개 완료! 진정한 실력자!",
    hint: "500개?! 거의 두 달치야! 진정한 실력자! 🥇",
    emoji: "🥇",
    grade: "epic",
    category: "milestone",
    condition: (ctx) => ctx.totalCompleted >= 500,
    repeatable: false,
  },
  {
    id: "total-750",
    name: "750개 돌파",
    description: "750개 완료! 정상을 향해!",
    hint: "750개! 정상이 보이기 시작했어! 🏔️",
    emoji: "🏔️",
    grade: "epic",
    category: "milestone",
    condition: (ctx) => ctx.totalCompleted >= 750,
    repeatable: false,
  },
  {
    id: "total-1000",
    name: "1000개 돌파",
    description: "1000개 완료! 네 자릿수 진입!",
    hint: "천 개! 네 자릿수의 세계에 오신 걸 환영해! 💎",
    emoji: "💎",
    grade: "epic",
    category: "milestone",
    condition: (ctx) => ctx.totalCompleted >= 1000,
    repeatable: false,
  },
  {
    id: "total-1500",
    name: "1500개 돌파",
    description: "1500개 완료! 절반을 넘었어!",
    hint: "전체의 절반을 넘겼어! 끝이 보인다! ⚡",
    emoji: "⚡",
    grade: "legendary",
    category: "milestone",
    condition: (ctx) => ctx.totalCompleted >= 1500,
    repeatable: false,
  },
  {
    id: "total-2000",
    name: "2000개 돌파",
    description: "2000개 완료! 최고의 도전자!",
    hint: "이천 개?! 이건 최고 중의 최고만 가능해! 🏆",
    emoji: "🏆",
    grade: "legendary",
    category: "milestone",
    condition: (ctx) => ctx.totalCompleted >= 2000,
    repeatable: false,
  },
  {
    id: "total-2500",
    name: "2500개 돌파",
    description: "2500개 완료! 역사에 남을 기록!",
    hint: "거의 다 왔어! 2500개 완료하면 역사에 이름을 남기는 거야! 👑",
    emoji: "👑",
    grade: "legendary",
    category: "milestone",
    condition: (ctx) => ctx.totalCompleted >= 2500,
    repeatable: false,
  },

  // ============================================================
  // 마일스톤 — 올클리어 일수
  // ============================================================
  {
    id: "perfect-1",
    name: "첫 올클리어",
    description: "처음으로 하루 할일을 모두 완료했어요!",
    hint: "하루 할일을 전부 끝내본 적 있어? 첫 올클에 도전! 🎉",
    emoji: "🎉",
    grade: "common",
    category: "milestone",
    condition: (ctx) => ctx.totalPerfectDays >= 1,
    repeatable: false,
  },
  {
    id: "perfect-5",
    name: "올클 5일",
    description: "5일이나 올클리어! 꾸준해요!",
    hint: "올클리어한 날이 5일이 되면! 연속 아니어도 돼~ ⭐",
    emoji: "⭐",
    grade: "common",
    category: "milestone",
    condition: (ctx) => ctx.totalPerfectDays >= 5,
    repeatable: false,
  },
  {
    id: "perfect-10",
    name: "올클 10일",
    description: "10일 올클리어! 진짜 잘하고 있어요!",
    hint: "올클리어한 날 10일 달성! 두 자릿수 올클러! 🌟",
    emoji: "🌟",
    grade: "common",
    category: "milestone",
    condition: (ctx) => ctx.totalPerfectDays >= 10,
    repeatable: false,
  },
  {
    id: "perfect-20",
    name: "올클 20일",
    description: "20일 올클리어! 습관의 달인!",
    hint: "20일이나 올클리어! 이 정도면 습관의 달인이지~ ✨",
    emoji: "✨",
    grade: "rare",
    category: "milestone",
    condition: (ctx) => ctx.totalPerfectDays >= 20,
    repeatable: false,
  },
  {
    id: "perfect-30",
    name: "올클 30일",
    description: "30일 올클리어! 한 달치를 해냈어요!",
    hint: "한 달치(30일) 올클리어! 진짜 대단한 거야~ 💫",
    emoji: "💫",
    grade: "rare",
    category: "milestone",
    condition: (ctx) => ctx.totalPerfectDays >= 30,
    repeatable: false,
  },
  {
    id: "perfect-50",
    name: "올클 50일",
    description: "50일 올클리어! 진정한 챔피언!",
    hint: "50일 올클리어! 진정한 챔피언만이 도달할 수 있어! 🏆",
    emoji: "🏆",
    grade: "epic",
    category: "milestone",
    condition: (ctx) => ctx.totalPerfectDays >= 50,
    repeatable: false,
  },
  {
    id: "perfect-75",
    name: "올클 75일",
    description: "75일 올클리어! 마스터의 길!",
    hint: "75일 올클! 마스터의 길을 걷고 있어! 🎖️",
    emoji: "🎖️",
    grade: "epic",
    category: "milestone",
    condition: (ctx) => ctx.totalPerfectDays >= 75,
    repeatable: false,
  },
  {
    id: "perfect-100",
    name: "올클 100일",
    description: "100일 올클리어! 전설의 마스터!",
    hint: "100일 올클리어... 전설의 마스터가 될 준비 됐어? 👑",
    emoji: "👑",
    grade: "epic",
    category: "milestone",
    condition: (ctx) => ctx.totalPerfectDays >= 100,
    repeatable: false,
  },
  {
    id: "perfect-150",
    name: "올클 150일",
    description: "150일 올클리어! 절반 이상을 완벽하게!",
    hint: "9개월 중 절반 이상을 올클! 진짜 대단해! 🌟",
    emoji: "💫",
    grade: "legendary",
    category: "milestone",
    condition: (ctx) => ctx.totalPerfectDays >= 150,
    repeatable: false,
  },
  {
    id: "perfect-200",
    name: "올클 200일",
    description: "200일 올클리어! 완벽에 가까운 여정!",
    hint: "270일 중 200일을 올클?! 거의 완벽한 인간... 🦄",
    emoji: "🦄",
    grade: "legendary",
    category: "milestone",
    condition: (ctx) => ctx.totalPerfectDays >= 200,
    repeatable: false,
  },

  // ============================================================
  // 마일스톤 — 참여 일수
  // ============================================================
  {
    id: "active-7",
    name: "1주일 참여",
    description: "7일 동안 할일이 있었어요!",
    hint: "뭉치와 함께한 지 7일! 벌써 일주일~ 📅",
    emoji: "📅",
    grade: "common",
    category: "milestone",
    condition: (ctx) => ctx.totalActiveDays >= 7,
    repeatable: false,
  },
  {
    id: "active-14",
    name: "2주 참여",
    description: "14일 동안 꾸준히 참여했어요!",
    hint: "2주(14일) 동안 꾸준히! 대단한 끈기야! 📅",
    emoji: "📅",
    grade: "common",
    category: "milestone",
    condition: (ctx) => ctx.totalActiveDays >= 14,
    repeatable: false,
  },
  {
    id: "active-30",
    name: "한 달 참여",
    description: "30일 동안 함께했어요!",
    hint: "뭉치와 한 달(30일)을 함께! 우리 친구 맞지? 📆",
    emoji: "📆",
    grade: "rare",
    category: "milestone",
    condition: (ctx) => ctx.totalActiveDays >= 30,
    repeatable: false,
  },
  {
    id: "active-60",
    name: "두 달 참여",
    description: "60일 동안 꾸준히!",
    hint: "60일이나 함께! 이제 떼려야 뗄 수 없는 사이~ 📆",
    emoji: "📆",
    grade: "rare",
    category: "milestone",
    condition: (ctx) => ctx.totalActiveDays >= 60,
    repeatable: false,
  },
  {
    id: "active-100",
    name: "100일 참여",
    description: "100일 동안 함께한 우리!",
    hint: "100일 기념! 뭉치와 백일잔치 하자! 🗓️",
    emoji: "🗓️",
    grade: "epic",
    category: "milestone",
    condition: (ctx) => ctx.totalActiveDays >= 100,
    repeatable: false,
  },
  {
    id: "active-150",
    name: "150일 참여",
    description: "150일! 반 이상을 함께!",
    hint: "절반을 넘겼어! 끝까지 같이 가자! 📆",
    emoji: "📆",
    grade: "epic",
    category: "milestone",
    condition: (ctx) => ctx.totalActiveDays >= 150,
    repeatable: false,
  },
  {
    id: "active-200",
    name: "200일 참여",
    description: "200일! 거의 다 왔어!",
    hint: "200일 함께! 정말 오래 같이했다~ 🗓️",
    emoji: "🗓️",
    grade: "legendary",
    category: "milestone",
    condition: (ctx) => ctx.totalActiveDays >= 200,
    repeatable: false,
  },
  {
    id: "active-270",
    name: "끝까지 함께",
    description: "270일! 처음부터 끝까지 함께한 친구!",
    hint: "3월부터 12월까지 하루도 빠짐없이! 진정한 동반자! 👼",
    emoji: "👼",
    grade: "legendary",
    category: "milestone",
    condition: (ctx) => ctx.totalActiveDays >= 270,
    repeatable: false,
  },

  // ============================================================
  // 주간 (weekly) — 매주 반복 획득 가능
  // ============================================================
  {
    id: "weekly-good",
    name: "좋은 한 주",
    description: "이번 주 달성률 70% 이상!",
    hint: "이번 주 달성률을 70% 이상 만들어봐! 📈",
    emoji: "📈",
    grade: "common",
    category: "weekly",
    condition: (ctx) => ctx.weekRate >= 0.7,
    repeatable: true,
  },
  {
    id: "weekly-mvp",
    name: "이번주 으뜸",
    description: "이번 주 달성률 90% 이상!",
    hint: "이번 주 달성률 90% 이상이면 으뜸! 거의 다 해야 해! 🥇",
    emoji: "🥇",
    grade: "rare",
    category: "weekly",
    condition: (ctx) => ctx.weekRate >= 0.9,
    repeatable: true,
  },
  {
    id: "weekly-perfect",
    name: "빈틈없는 한 주",
    description: "이번 주 달성률 100%!",
    hint: "일주일 동안 하나도 빠짐없이! 100% 완벽한 한 주! 💯",
    emoji: "💯",
    grade: "epic",
    category: "weekly",
    condition: (ctx) => ctx.weekRate === 1,
    repeatable: true,
  },

  // ============================================================
  // 스페셜 (special) — 특수 조건
  // ============================================================
  {
    id: "phoenix",
    name: "불사조",
    description: "어제 100%가 아니었는데 오늘 올클리어! 멋진 컴백!",
    hint: "어제 올클 못했어도 괜찮아! 오늘 올클하면 불사조 등장! 🔥",
    emoji: "🔥",
    grade: "epic",
    category: "special",
    condition: (ctx) =>
      ctx.yesterdayRate < 1 && ctx.todayRate === 1 && ctx.todayTotal > 0,
    repeatable: true,
  },
  {
    id: "together",
    name: "우리 함께!",
    description: "시현이와 미송이 모두 오늘 100% 달성!",
    hint: "형제자매 모두 올클리어! 둘이 힘을 합쳐봐! 🤝",
    emoji: "🤝",
    grade: "legendary",
    category: "special",
    condition: (ctx) =>
      ctx.todayRate === 1 && ctx.siblingTodayRate === 1 && ctx.todayTotal > 0,
    repeatable: true,
  },
  {
    id: "weekend-warrior",
    name: "주말 전사",
    description: "주말에도 올클리어! 쉬는 날도 열심히!",
    hint: "토요일이나 일요일에 올클리어! 놀고 싶은데 대단해~ 🛡️",
    emoji: "🛡️",
    grade: "rare",
    category: "special",
    condition: (ctx) =>
      (ctx.todayDayOfWeek === 0 || ctx.todayDayOfWeek === 6) &&
      ctx.todayRate === 1 &&
      ctx.todayTotal > 0,
    repeatable: true,
  },
  {
    id: "monday-fighter",
    name: "월요일 용사",
    description: "월요일에 올클리어! 한 주의 시작이 완벽!",
    hint: "월요일은 힘들잖아~ 그래도 올클하면 용사! 💥",
    emoji: "💥",
    grade: "rare",
    category: "special",
    condition: (ctx) =>
      ctx.todayDayOfWeek === 1 && ctx.todayRate === 1 && ctx.todayTotal > 0,
    repeatable: true,
  },
  {
    id: "friday-finish",
    name: "금요일 마무리왕",
    description: "금요일에 올클리어! 한 주의 마무리가 완벽!",
    hint: "불금인데 할일도 다 끝내?! 마무리의 달인! 🎊",
    emoji: "🎊",
    grade: "rare",
    category: "special",
    condition: (ctx) =>
      ctx.todayDayOfWeek === 5 && ctx.todayRate === 1 && ctx.todayTotal > 0,
    repeatable: true,
  },

  // ============================================================
  // 히든 뱃지 — 획득 전에는 보이지 않음!
  // ============================================================
  {
    id: "hidden-early-bird",
    name: "얼리버드",
    description: "아침에 가장 먼저 할일을 시작했어요!",
    hint: "???",
    emoji: "🐦",
    grade: "rare",
    category: "special",
    condition: (ctx) =>
      ctx.todayCompleted >= 1 &&
      ctx.todayTotal > 0 &&
      ctx.currentHourKST >= 6 &&
      ctx.currentHourKST < 8,
    repeatable: false,
    hidden: true,
  },
  {
    id: "hidden-both-perfect-3",
    name: "환상의 형제",
    description: "형제 모두 3일 연속 올클리어!",
    hint: "???",
    emoji: "👫",
    grade: "legendary",
    category: "special",
    condition: (ctx) =>
      ctx.streak >= 3 && ctx.siblingTodayRate === 1 && ctx.todayRate === 1,
    repeatable: false,
    hidden: true,
  },
  {
    id: "hidden-perfect-week-all",
    name: "완벽한 한 주의 달인",
    description: "일주일 동안 매일 올클! 주간 달성률도 100%!",
    hint: "???",
    emoji: "🌈",
    grade: "epic",
    category: "special",
    condition: (ctx) => ctx.streak >= 7 && ctx.weekRate === 1,
    repeatable: false,
    hidden: true,
  },
  {
    id: "hidden-sunday-hero",
    name: "일요일의 영웅",
    description: "일요일에도 올클! 쉬고 싶은데 대단해!",
    hint: "???",
    emoji: "🦸‍♂️",
    grade: "rare",
    category: "special",
    condition: (ctx) =>
      ctx.todayDayOfWeek === 0 && ctx.todayRate === 1 && ctx.todayTotal > 0,
    repeatable: false,
    hidden: true,
  },
  {
    id: "hidden-marathon",
    name: "마라토너",
    description: "50일 연속 올클 + 누적 500개 완료! 진정한 마라토너!",
    hint: "???",
    emoji: "🏃‍♂️",
    grade: "legendary",
    category: "special",
    condition: (ctx) => ctx.streak >= 50 && ctx.totalCompleted >= 500,
    repeatable: false,
    hidden: true,
  },
];

export const GRADE_ORDER: Record<BadgeGrade, number> = {
  common: 0,
  rare: 1,
  epic: 2,
  legendary: 3,
};
